site_name: Panconvert Documentation
site_url: http://panconvert.readthedocs.org
repository_url:
pages:
- ['index.md', 'Introduction']
- ['User_Guide/Basic_Usage.md', 'User Guide', 'Basic Usage']
- ['User_Guide/Customizing_Panconvert.md', 'User Guide', 'Customizing']
- ['User_Guide/Known_Problems.md', 'User Guide', 'Known Problems']
- ['User_Guide/Pandoc_Help.md', 'User Guide', 'Pandoc Help']
- ['User_Guide/Update.md', 'User Guide', 'Update']
- ['Xtras/Install_Instructions.md', 'Prerequisits', 'Install Instructions']
- ['Xtras/Build_Instructions.md', 'Developers', 'Building Binaries']
- ['changelog.md', 'Version History', 'Changelog']

